version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nestjs
    container_name: "nestjs"
    restart: unless-stopped
    environment:
      - BUILDREACT=false
      # - DB_ROOTURL=mongodb://
      # - DB_USER=root
      # - DB_PASS=pass12345
      # - DB_PORT=27017
      # - DB_SERVICENAME=mongodb
      # - NODE_ENV=production
    volumes:
      - type: bind
        source: ./frontend/build
        target: /home/node/app/frontend/build
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_started
    command: ./startup_dev.sh
  mongo:
    image: mongo:latest
    container_name: mongoContainer
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: testdb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_configs:/data/configdb
    # networks:
      # - backend
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # command: mongod

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      mongo:
        condition: service_started

volumes:
  mongodb_data:
  mongodb_configs:
